apiVersion: v1
kind: Namespace
metadata:
  name: goldpinger
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: okgolove
  namespace: goldpinger
spec:
  interval: 1m0s
  url: https://okgolove.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: okgolove
  namespace: goldpinger
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: goldpinger
      sourceRef:
        kind: HelmRepository
        name: okgolove
      interval: 5m
  releaseName: goldpinger
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    namespace: goldpinger
    service:
      type: NodePort
